//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace FootEd
{
    public partial class drilldetails
    {
        protected global::System.Web.UI.WebControls.Literal drillName;
        protected global::System.Web.UI.WebControls.Image drillImage;
        protected global::System.Web.UI.WebControls.Literal drillDescription;
        protected global::System.Web.UI.WebControls.Literal drillDuration;
    }
}